# Generated by Django 6.0.2 on 2026-02-26 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMemberPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='family_members/photos/%Y/%m/%d/', verbose_name='사진')),
                ('caption', models.CharField(blank=True, max_length=120, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_photos', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '가족 개인 사진',
                'verbose_name_plural': '가족 개인 사진',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=50, verbose_name='표시 이름')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='family_members/profile/%Y/%m/%d/', verbose_name='프로필 사진')),
                ('bio', models.CharField(blank=True, max_length=200, verbose_name='소개')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '가족 구성원 프로필',
                'verbose_name_plural': '가족 구성원 프로필',
            },
        ),
    ]
