# Generated by Django 6.0.2 on 2026-02-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_familymemberphoto_familymemberprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymemberprofile',
            name='emoji',
            field=models.CharField(blank=True, default='🙂', max_length=10, verbose_name='이모티콘'),
        ),
    ]
