# Generated by Django 6.0.2 on 2026-02-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_familymemberprofile_emoji'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='태그명')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='familypost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.tag', verbose_name='태그'),
        ),
    ]
