# Generated by Django 6.0.2 on 2026-02-26 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_tag_familypost_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='family_posts/multi/%Y/%m/%d/', verbose_name='추가 사진')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.familypost', verbose_name='기사')),
            ],
            options={
                'verbose_name': '기사 추가 사진',
                'verbose_name_plural': '기사 추가 사진',
                'ordering': ['created_at'],
            },
        ),
    ]
