# Generated by Django 6.0.2 on 2026-03-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_familypostcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='familypostcomment',
            name='emoji',
            field=models.CharField(choices=[('🙂', '🙂'), ('😀', '😀'), ('😍', '😍'), ('👏', '👏'), ('🎉', '🎉'), ('❤️', '❤️'), ('👍', '👍')], default='🙂', max_length=5, verbose_name='이모티콘'),
        ),
    ]
